apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  database_url: jdbc:mysql://mysql-service:3306/vaccinationcenterdb
  mysql-server: mysql-service
  mysql-database-name: vaccinationcenterdb
  mysql-user-username: root
  citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  mysql_citizen_db: citizendb
  restaurantdb_url: jdbc:mysql://mysql-service:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  restaurantdb: restaurantdb
  foodcataloguedb: foodcataloguedb